# Generated by Django 5.2.4 on 2025-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                help_text="Mobile number with country code",
                max_length=15,
                null=True,
            ),
        ),
    ]
