# Generated by Django 5.2.4 on 2025-10-03 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GridTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "grid_size",
                    models.IntegerField(
                        default=9, help_text="Grid size (e.g., 9 for 9x9)"
                    ),
                ),
                (
                    "grid_data",
                    models.JSONField(
                        help_text="Grid layout with '?' for question cells and shape IDs for fixed cells"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "shape_type",
                    models.CharField(
                        choices=[
                            ("circle", "Circle"),
                            ("square", "Square"),
                            ("triangle", "Triangle"),
                            ("diamond", "Diamond"),
                            ("star", "Star"),
                            ("hexagon", "Hexagon"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Hex color code (e.g., #FF0000)", max_length=7
                    ),
                ),
                ("svg_data", models.TextField(help_text="SVG path data for the shape")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image representation",
                        null=True,
                        upload_to="shapes/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_shapes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["shape_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShapeGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "solution_data",
                    models.JSONField(
                        help_text="Complete solution showing which shapes go where"
                    ),
                ),
                (
                    "max_time_minutes",
                    models.IntegerField(
                        default=30, help_text="Maximum time allowed in minutes"
                    ),
                ),
                (
                    "points_per_correct",
                    models.IntegerField(
                        default=10, help_text="Points awarded per correct placement"
                    ),
                ),
                (
                    "penalty_per_wrong",
                    models.IntegerField(
                        default=5, help_text="Points deducted per wrong placement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "available_shapes",
                    models.ManyToManyField(
                        help_text="Shapes available for this game",
                        related_name="games",
                        to="games.shape",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_shape_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grid_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shape_games",
                        to="games.gridtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShapeGameAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_state",
                    models.JSONField(
                        default=dict, help_text="Current placement of shapes"
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "accuracy",
                    models.FloatField(
                        default=0.0, help_text="Percentage accuracy (0-100)"
                    ),
                ),
                ("correct_placements", models.IntegerField(default=0)),
                ("incorrect_placements", models.IntegerField(default=0)),
                ("time_taken_seconds", models.IntegerField(default=0)),
                (
                    "shape_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="games.shapegame",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shape_game_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
    ]
