# Generated by Django 5.2.4 on 2025-10-03 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_gridtemplate_shape_shapegame_shapegameattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievement",
            old_name="earned_at",
            new_name="created_at",
        ),
        migrations.AlterUniqueTogether(
            name="achievement",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="achievement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="points_reward",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="achievement",
            name="requirement_type",
            field=models.CharField(
                choices=[
                    ("levels_completed", "Levels Completed"),
                    ("puzzles_solved", "Puzzles Solved"),
                    ("score_reached", "Score Reached"),
                    ("streak", "Consecutive Wins"),
                    ("speed", "Speed Completion"),
                    ("first_win", "First Win"),
                    ("speed_demon", "Speed Demon"),
                    ("perfectionist", "Perfectionist"),
                    ("puzzle_master", "Puzzle Master"),
                    ("region_expert", "Region Expert"),
                ],
                default="puzzles_solved",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="requirement_value",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.CharField(default="trophy", max_length=50),
        ),
        migrations.CreateModel(
            name="PuzzleLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_number", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("puzzles_required", models.PositiveIntegerField(default=10)),
                ("unlock_level", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["level_number"],
            },
        ),
        migrations.CreateModel(
            name="LevelPuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_in_level", models.PositiveIntegerField(default=1)),
                ("points_reward", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shape_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_assignments",
                        to="games.shapegame",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_puzzles",
                        to="games.puzzlelevel",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "order_in_level"],
                "unique_together": {("level", "shape_game")},
            },
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="achievement_type",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="user",
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="games.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="UserLevelProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puzzles_completed", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_score", models.PositiveIntegerField(default=0)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="games.puzzlelevel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["level__level_number"],
                "unique_together": {("user", "level")},
            },
        ),
        migrations.CreateModel(
            name="UserPuzzleAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("score_earned", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "level_puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="games.levelpuzzle",
                    ),
                ),
                (
                    "shape_game_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_attempt",
                        to="games.shapegameattempt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puzzle_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "unique_together": {("user", "level_puzzle")},
            },
        ),
    ]
