# Generated by Django 5.2.4 on 2025-10-04 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_rename_earned_at_achievement_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PuzzleGrid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "grid_size",
                    models.IntegerField(
                        choices=[(3, "3x3"), (4, "4x4"), (5, "5x5")], default=3
                    ),
                ),
                ("level_number", models.PositiveIntegerField()),
                (
                    "grid_layout",
                    models.JSONField(
                        help_text="Exact grid layout with shape positions and question marks"
                    ),
                ),
                (
                    "correct_answers",
                    models.JSONField(
                        help_text="Correct shape IDs for each question cell"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("max_attempts", models.IntegerField(default=3)),
                ("time_limit_minutes", models.IntegerField(default=10)),
                (
                    "available_shapes",
                    models.ManyToManyField(
                        related_name="puzzle_grids", to="games.shape"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_puzzle_grids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["level_number", "created_at"],
                "unique_together": {("level_number",)},
            },
        ),
        migrations.CreateModel(
            name="PuzzleAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answers",
                    models.JSONField(
                        default=dict,
                        help_text="User's current answers for question cells",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_taken_seconds", models.IntegerField(default=0)),
                ("is_correct", models.BooleanField(default=False)),
                ("score", models.IntegerField(default=0)),
                ("correct_answers_count", models.IntegerField(default=0)),
                ("total_questions", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grid_puzzle_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "puzzle_grid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="games.puzzlegrid",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "unique_together": {("user", "puzzle_grid", "attempt_number")},
            },
        ),
        migrations.CreateModel(
            name="UserPuzzleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_unlocked", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("best_score", models.IntegerField(default=0)),
                ("best_time_seconds", models.IntegerField(blank=True, null=True)),
                ("total_attempts", models.IntegerField(default=0)),
                ("first_completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "puzzle_grid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="games.puzzlegrid",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grid_puzzle_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["puzzle_grid__level_number"],
                "unique_together": {("user", "puzzle_grid")},
            },
        ),
    ]
